---
- hosts: lenovo-xcc
  connection: local
  name: Get firmware inventory
  gather_facts: False

  vars:
    datatype: FirmwareInventory

  tasks:
  - name: Define timestamp
    set_fact: timestamp="{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    run_once: true

  - name: Set Default rootdir
    set_fact: rootdir="./output"
    when: rootdir is undefined
    run_once: true

  - name: Set Default host
    set_fact: host={{baseuri}}
    when: host is undefined

  - name: Define file to place results
    set_fact: template={{rootdir}}/{{host}}/{{host}}_{{datatype}}_{{timestamp}}

  - name: Create dropoff directory for host
    file:
      path: "{{ rootdir }}/{{ host }}"
      state: directory
  - name: Get firmware inventory
    redfish_info:
      category: Update
      command: GetFirmwareInventory
      baseuri: "{{ baseuri }}"
      timeout: 20
    register: result

  - name: Set var firmware_entries
    set_fact:
      firmware_entries: "{{ result.redfish_facts.firmware.entries }}"

  - name: Get BMC firmware version
    set_fact:
      BMCFWVersion: "{{ [item.SoftwareId, item.Version] | join }}"
    when: item.Id == 'BMC-Primary'
    loop:
      "{{ firmware_entries }}"

  - debug: var=BMCFWVersion

  - name: Get UEFI firmware version
    set_fact:
      UEFIFWVersion: "{{ [item.SoftwareId, item.Version] | join }}"
    when: item.Id == 'UEFI'
    loop:
      "{{ firmware_entries }}"

  - debug: var=UEFIFWVersion

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
