---
- name: Get nodes data from LXCA
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Get nodes data from LXCA
      pylxca_module:
        login_user: "{{ lxca_user }}"
        login_password: "{{ lxca_password }}"
        auth_url: "{{ lxca_url }}"
        command_options: nodes
      register: rslt
      tags:
        - nodes

    - name: Show LXCA node result
      debug:
        var: rslt
